import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import NavMenu from "./components/NavMenu";

const inter = Open_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="p-4">
					<NavMenu />
					<div className="p-8 bg-white">{children}</div>
				</div>
			</body>
		</html>
	);
}
